### ISSUE TITLE
Not working in Mac os Catalina

### ISSUE THREAD

**Issue by nilushana** [bhagyas/osx-sinhalese-dictionary#2]
Thank you so much for this great app. I have recently updated my MacBookPro with MacOS Catalina. DictUnifier App is working. But once I drag the ifo file, the app getting close automatically.

**Comment by LinusTse28** [comment]
I am trouble in the same situation. Have you dealt with that?

**Comment by squallgold** [comment]
same trouble..

**Comment by MnkGitBox** [comment]
same problem here...😢

**Comment by bhagyas** [comment]
Thanks for reporting this issue, It should be working with the new commit. e71085637d05211f269dee495c647850d3079400

**Comment by kooomi** [comment]
same trouble, and I'm relying on this greatly😭
